### ISSUE TITLE
Strange hierarchy for include directory

### ISSUE THREAD

**Issue by bioinfornatics** [dlang-community/containers#126]
Dear,

Some dlang-community projects seem to have an extra directory for their include directory, such as:
- stdx-allocator
- containers
- msgpack
- dparse
...

To draw the picture, I take as example the containers project and build using meson:

```
$ ls /usr/include/d/containers/containers/
cyclicbuffer.d  dynamicarray.d  hashmap.d  hashset.d  immutablehashset.d  internal  openhashset.d  package.d  simdset.d 
 slist.d  treemap.d  ttree.d  unrolledlist.d
```

Why it is not : `/usr/include/d/containers`
Or why for (phobos/std) it is not `/usr/include/d/std/std`

Is it the expected or these `meson.build` should be fixed:
Example at [line 94](https://github.com/dlang-community/containers/blob/master/meson.build#L94)

replace:
```
install_subdir('src/containers/', install_dir: 'include/d/containers/')
```
to:
```
install_subdir('src/containers/', install_dir: 'include/d/')
```

Thanks

Have a good day

**Comment by ximion** [comment]
@bioinfornatics This is intentional. D compilers like LDC/GDC include `/usr/include/d/` by default. This means if we install module `xyz` in `/usr/include/d/xyz`, it will take precedence over include paths set manually during the build.
So, if you have installed your project, change something and the build it again, the older locally installed module will be used instead of the new, changed one. This is a source of many annoying subtle bugs, and we use subdirectories to avoid that.
(long-term I hope we can go for a `/usr/include/d/<project_name>/<version>/<module>` path and have dub use the same local source directory, but we're not there yet)

Of course one could change the D compilers to not include `/usr/include/d/` by default, but that would make poor backwards compatibility - so the extra subdir approach is the easiest and most painless solution currently.

**Comment by CyberShadow** [comment]
I guess this question was answered, closing :)
