### ISSUE TITLE
Can not writeln(hashset) directly

### ISSUE THREAD

**Issue by zhaopuming** [dlang-community/containers#42]
Have to use writeln(hashset[]).

is this design on purpose?

**Comment by Hackerpilot** [comment]
The reasons that this won't work are:
* HasSet isn't a forward range - calling popFront on it would actually remove items from the set, so it would be empty after the call to writeln.
* It's not copyable - the set's destructor releases the set's memory
* It does not have a `toString`

It's possible to implement toString for HashSet, but it has not been done yet. I'm not sure that it's worth the effort because as you pointed out simply slicing the set will give access to the items in the set for printing.

**Comment by zhaopuming** [comment]
Well I think it's more of a style/habbit thing. As a new user, I thought collections support toString, so when I encountered this, I was supprised that it does not work. I imagin this might occur to other newbies. But if you document it, I think it would be fine.

**Comment by Hackerpilot** [comment]
All classes support toString (Or at least the version they inherit from Object), but not all structs do.

**Comment by CyberShadow** [comment]
This is a general problem with non-copyable ranges. Partially the problem is with `writeln`, it does not support non-copyable types in general. In any case I think this is not actionable.

> As a new user, I thought collections support toString, so when I encountered this, I was supprised that it does not work. I imagin this might occur to other newbies.

I think new D users should stick to standard D facilities, such as the built in associative arrays instead of `HashMap`. Using this library effectively requires understanding of advanced topics like allocators and lifetime.
