### ISSUE TITLE
Concurrent containers?

### ISSUE THREAD

**Issue by Stretto** [dlang-community/containers#61]
How hard would it be to make these containers concurrent? A few locks here and there would do. A user defined lock could be used so only locking is needed, which also could be statically compiled in if the user defined lock is specified. (So no locking method specified = single threaded, else multi-threaded)

**Comment by Hackerpilot** [comment]
> How hard would it be to make these containers concurrent?
The answer to this question would probably only be available after some very subtle bug is discovered a year after making them concurrent.

**Comment by rjmcguire** [comment]
Hi,

Rather use a wrapper struct that controls access. You can then play with
different kinds of locking patterns.

I'd imagine as long as the wrapper methods are inlined you shouldn't have
issues doing your own wrapper vs the container having even more code added
to it.

On 03 Sep 2016 01:15, "Stretto" <notifications@github.com> wrote:

How hard would it be to make these containers concurrent? A few locks here
and there would do. A user defined lock could be used so only locking is
needed, which also could be statically compiled in if the user defined lock
is specified. (So no locking method specified = single threaded, else
multi-threaded)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/economicmodeling/containers/issues/61>, or mute the
thread

**Comment by Stretto** [comment]
Subtle bugs are not an "excuse". Since D can easily add compile time differentiation between ST and MT, the ST containers won't be affected, so it is app upside. A simple warning about potential bugs in the MT is all that is required. When bugs do come up, they then can be fixed. 

The problem with doing it myself is maintainability and strength testing. While I could fork and work on that, I'm sure my MT skills are not as great as others.  I don't see why it would a lot of work though. wrapping the critical code in a CT lock shouldn't be that difficult? For ST, the code is compiled out and should have no effect on performance. For MT code, it at least provides some level of safety and any future bugs can then be dealt with. Some testing could be done and what not to attempt to find the bugs. More subtle bugs can be dealt with by a larger user base.

**Comment by rjmcguire** [comment]
On 03 Sep 2016 14:41, "Stretto" <notifications@github.com> wrote:
>
> Subtle bugs are not an "excuse". Since D can easily add compile time
differentiation between ST and MT, the ST containers won't be affected, so
it is app upside. A simple warning about potential bugs in the MT is all
that is required. When bugs do come up, they then can be fixed.
>
> The problem with doing it myself is maintainability and strength testing.
While I could fork and work on that, I'm sure my MT skills are not as great
as others. I don't see why it would a lot of work though. wrapping the
critical code in a CT lock shouldn't be that difficult? For ST, the code is
compiled out and should have no effect on performance. For MT code, it at
least provides some level of safety and any future bugs can then be dealt
with. Some testing could be done and what not to attempt to find the bugs.
More subtle bugs can be dealt with by a larger user base.
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub, or mute the thread.

It's not a difficulty thing it's a design decision thing.

Granted this is already a library with a bunch of semi-related code in it
so you may get your wish. I would be interested to see if others also think
adding MT would be a good addition to the core library.

**Comment by CyberShadow** [comment]
My understanding is that you need to design containers from the ground up to be effectively concurrent, so I think this would be a task for a different library entirely. Granularity and mechanism of locking is also highly sensitive to the application at hand, so a general-purpose library is unlikely to fit all applications well. As such let's close this issue because it's not really actionable.

**Comment by mw66** [comment]
Actually, can we add to the doc: this library is not thread-safe? I think this is very important information to let the users be aware of.
